#!/bin/bash
set -e
# Necessary for the backend to work, against debian policy.
chmod 700 /usr/lib/cups/backend/cups-pdf-dpt
service cups start
lpadmin -p "DPT-RP1" -D "Sony Digital Paper" -v cups-pdf-dpt:/ -E -P /usr/share/cups/model/CUPS-PDF-DPT.ppd
